# Generated by Django 4.1.7 on 2023-04-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.TextField(default='null value', max_length=1000),
            preserve_default=False,
        ),
    ]
