# Generated by Django 4.1.7 on 2023-04-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='rhih', max_length=70),
        ),
    ]
